[kubernetes]
disabled = true
format = '\[[$context:$namespace](dimmed blue)\] '
[kubernetes.context_aliases]
"admin@.*" = "ðŸ”¥$0ðŸ”¥"

[package]
disabled = true
[java]
disabled = true
[git_status]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[python]
disabled = true
[docker_context]
disabled = true
[nodejs]
disabled = true
[vagrant]
disabled = true
[lua]
disabled = true
[golang]
disabled = false
# [line_break]
# disabled = true
[time]
disabled = false
[kotlin]
disabled = true
[aws]
format = '[($profile) (\($region\)) (\[$duration\])]($style)'
[status]
disabled = false

[directory]
# truncation_length = 2
truncate_to_repo = true

[gcloud]
disabled = true
# detect_env_vars	= [] # activate when these are set

[terraform]
disabled = true
format = '[tf $version]($style) '

[shell]
disabled = false
style = 'cyan bold'
