[kubernetes]
disabled = true
format = '\[[$context:$namespace](dimmed blue)\] '
[kubernetes.context_aliases]
"admin@.*" = "ğŸ”¥$0ğŸ”¥"

[package]
disabled = true
[java]
disabled = true
[git_status]
disabled = true
[python]
disabled = true
[docker_context]
disabled = true
[nodejs]
disabled = true
[vagrant]
disabled = true
[lua]
disabled = true
[golang]
disabled = true
# [line_break]
# disabled = true
[time]
disabled = false
[kotlin]
disabled = true
[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
